import type { MaterialProfile } from './pricing-types';

export const materialCatalogVersion = 1;

export const defaultMaterials: MaterialProfile[] = [
  {
    id: 'pla',
    name: 'PLA',
    process: 'fdm',
    description: 'Low-cost prototyping material with good dimensional stability.',
    descriptionEn: 'Low-cost prototyping material with good dimensional stability.',
    densityGPerCm3: 1.24,
    materialPricePerG: 0.08,
    surfaceAreaPricePerMm2: 0.000012,
    supportRate: 0,
    failureRate: 0.08,
    postProcessFee: 0,
    materialMinimumCharge: 18,
    markupRate: 0.35,
    leadTimeDays: 3,
    enabled: true,
  },
  {
    id: 'petg',
    name: 'PETG',
    process: 'fdm',
    description: 'Durable FDM material for functional parts and brackets.',
    descriptionEn: 'Durable FDM material for functional parts and brackets.',
    densityGPerCm3: 1.27,
    materialPricePerG: 0.1,
    surfaceAreaPricePerMm2: 0.000012,
    supportRate: 0,
    failureRate: 0.09,
    postProcessFee: 0,
    materialMinimumCharge: 22,
    markupRate: 0.35,
    leadTimeDays: 3,
    enabled: true,
  },
  {
    id: 'abs',
    name: 'ABS',
    process: 'fdm',
    description: 'Impact-resistant material for functional prototypes, with higher warping risk.',
    descriptionEn: 'Impact-resistant material for functional prototypes, with higher warping risk.',
    densityGPerCm3: 1.04,
    materialPricePerG: 0.12,
    surfaceAreaPricePerMm2: 0.000014,
    supportRate: 0,
    failureRate: 0.14,
    postProcessFee: 0,
    materialMinimumCharge: 25,
    markupRate: 0.38,
    leadTimeDays: 4,
    enabled: true,
  },
  {
    id: 'pa12',
    name: 'Nylon PA12',
    process: 'sls',
    description: 'Strong SLS nylon for end-use functional parts and complex geometries.',
    descriptionEn: 'Strong SLS nylon for end-use functional parts and complex geometries.',
    densityGPerCm3: 1.01,
    materialPricePerG: 0.22,
    surfaceAreaPricePerMm2: 0.00002,
    supportRate: 0,
    failureRate: 0.07,
    postProcessFee: 0,
    materialMinimumCharge: 38,
    markupRate: 0.4,
    leadTimeDays: 5,
    enabled: true,
  },
  {
    id: 'resin',
    name: 'Standard Resin',
    process: 'sla',
    description: 'High-detail SLA resin for visual models and precise prototypes.',
    descriptionEn: 'High-detail SLA resin for visual models and precise prototypes.',
    densityGPerCm3: 1.18,
    materialPricePerG: 0.18,
    surfaceAreaPricePerMm2: 0.000024,
    supportRate: 0,
    failureRate: 0.1,
    postProcessFee: 4,
    materialMinimumCharge: 30,
    markupRate: 0.42,
    leadTimeDays: 4,
    enabled: true,
  },
  {
    id: 'aluminum',
    name: 'Aluminum AlSi10Mg',
    process: 'slm',
    description: 'Metal additive manufacturing option for lightweight engineering parts.',
    descriptionEn: 'Metal additive manufacturing option for lightweight engineering parts.',
    densityGPerCm3: 2.68,
    materialPricePerG: 1.4,
    surfaceAreaPricePerMm2: 0.00008,
    supportRate: 0,
    failureRate: 0.12,
    postProcessFee: 18,
    materialMinimumCharge: 95,
    markupRate: 0.45,
    leadTimeDays: 8,
    enabled: true,
  },
];
